project:
  type: book
  preview:
    port: 4200

editor:
  render-on-save: true
book:
  title: "Graviational Waves from Feynman Diagrams"
  author: "Lucien Huber"
  date: "9/13/2022"
  search: true
  repo-url: https://github.com/lcnhb/GWAmplitudes
  repo-actions: [edit]
  downloads: [pdf, epub]
  

  chapters:
    - index.qmd
    - intro.qmd
    - gwsources.qmd
    - gwdetect.qmd
    - gwwfframeworks.qmd
    - scattering.qmd
    - summary.qmd
    - references.qmd
crossref:
  fig-title: Fig     # (default is "Figure")
  tbl-title: Tbl     # (default is "Table")
  eq-title: Eqn     # (default is "Equation")
  eq-prefix: " "
comments:
  hypothesis: true

bibliography: references.bib
reference-location: margin
citation-location: document
fig-cap-location: margin
execute:
  freeze: auto  # re-render only when source changes




filters: 
  - assets/lua/parse_acronyms.lua
  - assets/lua/not-in-format.lua
  - assets/lua/diagram-generator.lua
acronyms:
  style: long-short
  insert_loa: false
  insert_links: false
  keys:
    - shortname: Rmd
      longname: Rmarkdown document
    - key: yaml
      shortname: YAML
      longname: YAML Ain't Markup Language
    - key: ligo
      shortname: LIGO
      longname: Laser Interferometer Gravitational-Wave Observatory
    - key: gw
      shortname: GW
      longname: Gravitational Wave
    - key: bh
      shortname: BH
      longname: Black Hole
    - key: ns
      shortname: NS
      longname: Neutron Star
    - key: bbh
      shortname: BBH
      longname: Binary Black Hole
    - key: bns
      shortname: BNS
      longname: Binary Neutron Star
    - key: eob
      shortname: EOB
      longname: Effective One-Body
    - key: pm
      shortname: PM
      longname: Post-Minkowski
    - key: pn
      shortname: PN
      longname: Post-Newtonian
    - key: gr
      shortname: GR
      longname: General Relativity
    - key: sr
      shortname: SR
      longname: Special Relativity
    - key: nr
      shortname: NR
      longname: Numerical Relativity
    - key: nrgr
      shortname: NRGR
      longname: Nonrelativistic General Relativity
    - key: eft
      shortname: EFT
      longname: Effective Field Theory
    - key: qft
      shortname: QFT
      longname: Quantum Field Theory
    - key: qm
      shortname: QM
      longname: Quantum Mechanics
    - key: lisa
      shortname: LISA
      longname: Laser Interferometer Space Antenna 
    - key: lhs
      shortname: LHS
      longname: Left-Hand Side
    - key: rhs
      shortname: RHS
      longname: Right-Hand Side
    - key: em
      shortname: EM
      longname: Electromagnetism
    - key: efe
      shortname: EFE
      longname: Einstein Field Equations
    - key: eom
      shortname: EOM
      longname: Equation of Motion
    - key: lsz
      shortname: LSZ
      longname: Lehmann Symanzik and Zimmermann
    - key: kmoc
      shortname: KMOC
      longname: Kosower Maybee and O'Connell
    - key: sqed
      shortname: SQED
      longname: Scalar Quantum Electrodynamics
    - key: qed
      shortname: QED
      longname: Quantum Electrodynamics
    - key: qcd  
      shortname: QCD
      longname: Quantum Chromodynamics
    - key: gsf
      shortname: GSF
      longname: Gravitational Self-Force
    - key: lhc
      shortname: LHC
      longname: Large Hadron Collider
    - key: lsco
      shortname: LSCO
      longname: Last Stable Circular Orbit
    - key: coma
      shortname: COM
      longname: Center of Mass
    - key: com
      shortname: COM
      longname: Center of Momentum
    - key: ibp
      shortname: IBP
      longname: Integration by Parts

    
    


pdf-engine: lualatex

format:
  html:
    theme: [assets/css/theme.scss]
#   css: assets/css/tufte.css
    code-fold: true
    code-tools: true
    default-image-extension: svg
    
  pdf:
    from: markdown-latex_macros
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{amsmath}
        \usepackage{mathtools}
        \usepackage{cancel}
        \usepackage{svg}
        \usepackage{adjustbox}
    include-before-body: 
      - latexmacros.tex
      - latexfix.tex
    default-image-extension:  tex

    
    



