project:
  type: book
  preview:
    port: 4200

editor:
  render-on-save: true
book:
  title: "Gravitational Waves from Feynman Diagrams"
  author: "Lucien Huber"
  date: "9/13/2022"
  search: true
  repo-url: https://github.com/lcnhb/GWAmplitudes
  repo-actions: [edit]
  downloads: [pdf]
  abstract: |

      The goal of this thesis is to explain the nascent field of scattering amplitudes in gravitational wave physics. We explore the context in which these tools are revolutionizing the field, and then go into detail of their construction and application. 

      We begin with a brief overview of the topic and the academic context. The next chapter is devoted to the theoretical foundations of gravitational waves, and their important sources. In the third chapter we discuss the detection of these waves, highlighting the importance of the theoretical templates. The fourth chapter explores the theoretical methods for producing full wave templates, such as (?:eob) and (?:nr) as well as the expansions and approximations used for the inspiral: the (?:pn) and (?:pm) approximations. 

      The fifth chapter is the main focus of the thesis, and is devoted to the scattering amplitude techniques that can be applied to the general relativistic two-body problem. We begin with the (?:eft) matching technique to motivate the production of gravitational amplitudes. The (?:kmoc) formalism, defining the classical limit of wave functions, is explained in detail. Finally, amplitudes in a simplified theory, (?:sqed) are computed, with a focus on automation of calculations. The corresponding graphs, filters, Feynman rules and further simplifications are all implemented in a cocktail of the relevant languages. We also compare the results obtained with those found in the literature.
      
      In the last chapter we provide some concluding remarks and a brief outlook.
  

  chapters:
    - index.qmd
    - acknowledgements.qmd
    - intro.qmd
    - gwsources.qmd
    - gwdetect.qmd
    - gwwfframeworks.qmd
    - scattering.qmd
    - conclusion.qmd
    - references.qmd
crossref:
  fig-title: Fig     # (default is "Figure")
  tbl-title: Tbl     # (default is "Table")
  eq-title: Eqn     # (default is "Equation")
  eq-prefix: "eq."
comments:
  hypothesis: true

bibliography: references.bib
reference-location: margin
link-citations: true
fig-cap-location: margin
subfig-cap-location: bottom
execute:
  freeze: auto  # re-render only when source changes
  cache: true

keep-tex: true


filters:   
  - assets/lua/parse_acronyms.lua
  - assets/lua/diagram-generator.lua
acronyms:
  style: long-short
  insert_loa: false
  insert_links: false
  keys:
    - shortname: Rmd
      longname: Rmarkdown document
    - key: yaml
      shortname: YAML
      longname: YAML Ain't Markup Language
    - key: ligo
      shortname: LIGO
      longname: Laser Interferometer Gravitational-Wave Observatory
    - key: gw
      shortname: GW
      longname: Gravitational Wave
    - key: bh
      shortname: BH
      longname: Black Hole
    - key: ns
      shortname: NS
      longname: Neutron Star
    - key: bbh
      shortname: BBH
      longname: Binary Black Hole
    - key: smbh
      shortname: SMBH
      longname: Supermassive Black Hole
    - key: imri
      shortname: IMRI
      longname: Intermediate Mass Ratio Inspiral
    - key: emri
      shortname: EMRI
      longname: Extreme Mass Ratio Inspiral
    - key: bns
      shortname: BNS
      longname: Binary Neutron Star
    - key: eob
      shortname: EOB
      longname: Effective One-Body
    - key: pm
      shortname: PM
      longname: Post-Minkowski
    - key: pn
      shortname: PN
      longname: Post-Newtonian
    - key: gr
      shortname: GR
      longname: General Relativity
    - key: sr
      shortname: SR
      longname: Special Relativity
    - key: nr
      shortname: NR
      longname: Numerical Relativity
    - key: nrgr
      shortname: NRGR
      longname: Nonrelativistic General Relativity
    - key: eft
      shortname: EFT
      longname: Effective Field Theory
    - key: qft
      shortname: QFT
      longname: Quantum Field Theory
    - key: qm
      shortname: QM
      longname: Quantum Mechanics
    - key: lisa
      shortname: LISA
      longname: Laser Interferometer Space Antenna 
    - key: lhs
      shortname: LHS
      longname: Left-Hand Side
    - key: rhs
      shortname: RHS
      longname: Right-Hand Side
    - key: em
      shortname: EM
      longname: Electromagnetism
    - key: efe
      shortname: EFE
      longname: Einstein Field Equations
    - key: eom
      shortname: EOM
      longname: Equation of Motion
    - key: lsz
      shortname: LSZ
      longname: Lehmann Symanzik and Zimmermann
    - key: kmoc
      shortname: KMOC
      longname: Kosower Maybee and O'Connell
    - key: sqed
      shortname: SQED
      longname: Scalar Quantum Electrodynamics
    - key: qed
      shortname: QED
      longname: Quantum Electrodynamics
    - key: qcd  
      shortname: QCD
      longname: Quantum Chromodynamics
    - key: gsf
      shortname: GSF
      longname: Gravitational Self-Force
    - key: lhc
      shortname: LHC
      longname: Large Hadron Collider
    - key: lsco
      shortname: LSCO
      longname: Last Stable Circular Orbit
    - key: coma
      shortname: COM
      longname: Center of Mass
    - key: com
      shortname: COM
      longname: Center of Momentum
    - key: ibp
      shortname: IBP
      longname: Integration by Parts
    - key: amr
      shortname: AMR
      longname: Adaptive Mesh Refinement
    - key: gh
      shortname: GH
      longname: Generalized Harmonic
    - key: nrqcd
      shortname: NRQCD
      longname: Non-Relativistic Quantum Chromodynamics
    - key: lo
      shortname: LO
      longname: Leading Order
    - key: nlo
      shortname: NLO
      longname: Next-to-Leading Order
    - key: nnlo
      shortname: NNLO
      longname: Next-to-Next-to-Leading Order
    - key: nnnlo  
      shortname: NNNLO
      longname: Next-to-Next-to-Next-to-Leading Order
    - key: nnnnlo
      shortname: NNNNLO
      longname: Next-to-Next-to-Next-to-Next-to-Leading Order
    - key: pta
      shortname: PTA
      longname: Pulsar Timing Array
    - key: toa
      shortname: ToA
      longname: Time of Arrival
    - key: nsbh
      shortname: NS-BH
      longname: Neutron Star - Black Hole
    - key: hep
      shortname: HEP
      longname: High Energy Physics 
  

    
csl: physical-review-letters.csl

pdf-engine: lualatex

format:
  html:
    theme: [assets/css/theme.scss]
#   css: assets/css/tufte.css
    code-fold: true
    code-tools: true
    default-image-extension: svg
    
  pdf:
    keep-tex: true
    fontsize: "11pt"
    from: markdown-latex_macros
    documentclass: scrreprt
    papersize: a4
    colorlinks: true
    include-in-header: preamble.tex
    include-before-body: 
      - latexmacros.tex
      - latexfix.tex
    default-image-extension:  tex

    
    



