::: {.content-hidden unless-format="html"}

{{< include _latexmacros.qmd >}}

:::
$$
\begin{aligned}
\Delta O_\text{r}=\sum\limits_X \int \ddP[2+\abs{X}]{r_1,&r_2,X}\,\ddP[2]{p_1,p_2} \dh[4]q\,\hat{\delta}(2 p_1 \cdot q+q^2) \Theta(p^0_1+q^0)\\
&\times \hat{\delta}(2 p_2 \cdot q-q^2) \Theta(p^0_2-q^0)\\
&\times\phi_1(p_1)\phi_2(p_2)\phi_1^\dagger(p_1+q)\phi_2^\dagger(p_2-q)\,\exp{-\frac{\i}{\hbar} b_\mu q^\mu}\\
&\times\underset{rX-p}{\Delta}\!\! O \,\hat{\delta}^{(4)}\left(p_{1}+p_{2}-r_{1}-r_{2}-r_{X}\right) \\
&\times   \mathcal{A}\left(p_{1}, p_{2} \rightarrow r_{1}, r_{2}, r_{X}\right) \mathcal{A}^{*}\left(p_{1}+q, p_{2}-q \rightarrow r_{1}, r_{2}, r_{X}\right)
\end{aligned}$${#eq-DeltaOr}

# Classical limit

Since we are concerned with classial observables we need to explore the classical limit of #^DeltaO, i.e. the limit of $\hbar \to 0$. The first target is the wavefunctions. 

## Classical limit of wavefunctions

In \acr{kmoc} framework|\acr{kmoc} we are interested in the classical limit of a scattering event. It is then important to understand the precise simplifications this limit yields. 


We have multiple conditions on the wavefunctions. The first are those imposed by LSZ reduction|LSZ. That is,

- Compact support momentum space wavefunction in QFT|wavefunction
- Peaked around one value of momenta

Classical limit of the wavefunctions should make sense, thus 

- as $\hbar \to 0$ the wavefunction should approach a delta function
- The spread should not be too large as to interact between the two initial states
- The overlap between the wavefunction and its conjugate should be nearly full, since they represent the same particle classically.

Consider for example a nonrelativistic wavefunction:

$$f(\mathbf{p})=-\exp\pqty\bigg{-\frac{\mathbf{p}}{2 \hbar m \ell_c/\ell_\omega^2}}\stackrel{\hbar=\ell_c m}{=}\exp\qty\bigg(-\frac{\mathbf{p}}{2 m^2 \ell_c^2 /\ell_\omega^2})$$
This wavefunction grows sharper in the $\hbar \to 0$ limit. 

The Fourier transform of $f(\mathbf{p})$ gives us the position "probability density":
$$\begin{align*}
f(\mathbf{x})&=\int \frac{\dd{p}}{2 \pi} \exp\pqty\Big{-\pqty\Big{\frac{\mathbf{p}}{A}}^2}\exp\pqty\Big{-\frac{\iunit}{\hbar} \mathbf{p}\cdot \mathbf{x}}\\
&=\frac{1}{2\pi}\underbracket{\int \dd{p} \exp\pqty\Big{-\pqty\Big{\frac{\mathbf{p}}{A}-\frac{\iunit\mathbf{x}A}{2 \hbar}}^2}}_{\sqrt{\pi}A}\exp\pqty\Big{- \frac{\mathbf{x}^2A}{4 \hbar^2}}\\
&=\frac{\sqrt{2}A}{2 \pi}\exp\pqty\Big{-\frac{\mathbf{x}^2}{2 \ell_\omega^2}}
\end{align*}$$
[^x0]
This wavefunction grows sharper in the $\ell_\omega^2 \to 0$ limit. We must then still have that $\xi=\pqty{\frac{\ell_c}{\ell_\omega}}^2\to0$ when $\hbar \to 0$ as-well. This works if we just directly take the classical limit to be the $\xi \to 0$ limit.


Going back to the general conditions we want $\phi_i(p_i)$ s.t:

- $\ev{p^\mu_i}=\int \dd{\Phi(p_i)} p^\mu_i \abs{\phi_i(p_i)}^2\stackrel{!}{=}m_i \breve{u}_i^\mu f_{p,i}(\xi)$[^1] with $f_{p,i}(\xi)=1+\mathcal{O}(\xi^{\beta'})$
- $\sigma^2(p_i)/m_i^2=\ev{(p_i-\ev{p_i})^2}/m_i^2=(\ev{p^2_i}-\ev{p_i}^2)/m_i^2=c_\Delta\xi^\beta$[^2]
- $\breve{u}_i \cdot u_i = 1+ \mathcal{O}(\xi^{\beta''})$[^3]

Additionally the wavefunction should be Lorentz invariant, thus naively we would have that $\phi(p_i^\mu)=\tilde{\phi}(p_i^2)$ however the integration measure enforces an on shell condition: $m_i^2=p_i^2$. Thus the wavefunction cannot usefully depend on $p_i^2$, we need to introduce at least one additional four vector parameter $u$. The simplest dimensionless combination of parameters it then $\frac{p \cdot u }{m}$. Of course the wavefunction must also depend on $\xi$ and the simplest form of argument will thus be $\frac{p \cdot u }{m \xi}$ so that any $p$ not aligned with $u$ will be strongly suppressed in the $\xi \to0$ limit.

We now have control over most of the conditions:

- The classical limit is well defined
- The wavefunction spread is controlled
- The arguments of the wavefunction is clear

The last requirement concerns the overlap of $\phi$ and $\phi^\dagger$ must be $\mathcal{O}(1)$, equivalently and more precisely:

$$\phi^\dagger(p+q)\sim \phi^\dagger(p) \implies \phi^\dagger(p+q)- \phi^\dagger(p)\ll 1 \implies q^\mu\partial_\mu{\phi^\dagger}(p)\ll1$$
Making explicit the $\frac{p \cdot u }{m \xi}$ dependence: $\phi(p)=\varphi(\frac{p \cdot u }{m \xi})$   for $\varphi(x)$ a scalar function.
$$\implies \frac{q^\mu u_\mu}{m \xi}\pdv{\varphi^\dagger}{x}(\frac{p \cdot u }{m \xi})\ll1$$
Thus we require that for a characteristic value of $q=q_0$ we have:

$$\frac{q_0\cdot u}{m \xi}=\bar{q}_0 \cdot u\frac{\ell_\omega^2}{\ell_c}\ll1\iff \bar{q}_0 \cdot u\,\ell_\omega\ll \sqrt{ \xi}$$[^4]
We now want to examine the classical limit of something like  \acr{kmoc} framework#^deltaOv. If we consider just the integration over the initial momenta $p_i$ and the initial wavefunctions with $\hat{\delta}(2 p_i \cdot q+q^2)$, the delta function will smear out to a sharply peaked function whose scale is the same order as the original wavefunctions. As $\xi$ gets smaller, this function will turn back into a delta function  
imposed on the $q$ integration.[^5] Let us examine this statement more closely:


$$d(m,\xi,u,q)=\int \dd{\Phi(p)} \hat{\delta}(2 p \cdot q+q^2) \Theta(p^0+q^2)\varphi(\frac{p \cdot u }{m \xi})\varphi^\dagger(\frac{(p+q) \cdot u }{m \xi})$$
^dfunct

This integral must be Lorentz invariant and depends on $m,\xi, u,q$ thus it must manifestly only depend on the following math/Lorentz group|Lorentz invariants: $u^2,q^2,u \cdot q, \xi$. One of these is not actually a variable as we will normalise $u^2=1$. The rest aren't fully dimensionless, and we can render them dimensionless:[^6]

$$\begin{align*}
[q^2]&=[\hbar \bar{q}]^2=[M]^2\implies[\ell_c \sqrt{-\bar{q}^2}]=[\frac{\hbar}{m}\sqrt{-\bar{q}^2}]=\frac{[M]}{[M]}=1\\
[u \cdot q]&=[M]\implies [\frac{u \cdot\bar{q}}{\sqrt{-\bar{q}^2}}]= [\frac{u \cdot{q}}{\sqrt{-{q}^2}}]=\frac{[M]}{[M]}=1\\
[\xi]&=1
\end{align*}$$
If we call $\frac{1}{\sqrt{-\bar{q}^2}}=\ell_s$ a scattering length[^7] then our dimensionless ratios are :

$$\frac{\ell_c}{\ell_s} \qqtext{and} \ell_s\,\bar{q} \cdot u $$
The delta function can be rewritten as:
$$\hat{\delta}(2 p \cdot q+q^2)=\hat{\delta}(2\hbar m\, u\cdot \bar{q}+\hbar^2 \bar{q}^2)=\frac{1}{\hbar m}\hat{\delta}(2 \bar{q} \cdot u-\frac{\ell_c}{\ell_s^2})=\frac{\ell_s}{\hbar m}\hat{\delta}(2\ell_s\, \bar{q} \cdot u-\frac{\ell_c}{\ell_s})$$




[^1]: $A$ absorbs the various constants, with $A=\sqrt{2}m\frac{\ell_c}{\ell_\omega}$ and $\mathbf{x}_0$ 
[^2]: This means that the classical value of momentum $m_i \breve{u}_i^\mu$ is reached in the $\xi \to 0$ limit
[^3]: This encodes the limit of the spread as $\xi \to0$. $\ev{p_i^2}=m_i^2$ is enforced by the measure $\dd{\Phi(p)}$
[^4]: This enforces the normalisation condition $\breve{u}_i^2=1$ in the $\xi \to0$ limit 
[^5]: Here $\bar{q}=\frac{q}{\hbar}$ is the wavenumber
relativistically natural units|^6
relativistically natural units|^7 $[\frac{1}{\sqrt{-\bar{q}^2}}]=[T]=[L]=[\ell_s]$
example wavefunction in \acr{kmoc}|^8

classical limit of wavefuctions in \acr{kmoc}

## Notation

As we have now seen the phase space integrals over initial momenta, and over the wavefunctions can be readily eliminated in the classical limit, in which case the momenta $p_1$ and $p_2$ can be replaced by their classical values. To make explicit that idea we introduce the following notation:



$$\AAngle{f(p_1,p_2,\dots)}\def \int\limits \ddP{p_1}\ddP{p_2} \abs{\phi_1(p_1)}^2\abs{\phi_2(p_2)}^2\,f(p_1,p_2,\dots)$$

We can now rewrite #^deltaO:

$$\Delta O= \AAngle{\int \overbracket{\dh[4]{q} \hat{\delta}(2p_1\cdot q +q^2)\Theta(p^0_1+q^0)  \hat{\delta}(2p_1\cdot q +q^2)\Theta(p^0_2+q^0)}^{\dd{\Psi(q)}}\exp({-\frac{\i}{\hbar}}q^\mu b_\mu)\par[\Big]{\mathcal{I}_\text{v}'(O)+\mathcal{I}_\text{r}'(O)} }$$

Where 
$$\begin{aligned}
\mathcal{I}_\text{v}'(O)&=\i\,  \underset{q}{\Delta} O\, \mathcal{A}(p_1,p_2 \to p_1+q,p_2-q)\\
\mathcal{I}_\text{r}'(O)&=\sum\limits_X \int \ddP[2+\abs{X}]{r_1,r_2,X}\underset{rX-p}{\Delta}\!\! O \,\hat{\delta}^{(4)}\left(p_{1}+p_{2}-r_{1}-r_{2}-r_{X}\right) \\
&\times   \mathcal{A}\left(p_{1}, p_{2} \rightarrow r_{1}, r_{2}, r_{X}\right) \mathcal{A}^{*}\left(p_{1}+q, p_{2}-q \rightarrow r_{1}, r_{2}, r_{X}\right)


\end{aligned}$$

Additionally we want to make clear the dependence on $\hbar$ since we want to eventually take the $\hbar \to0$ limit. We can change integration variables to $\bar{q}=\frac{q}{\hbar}$ and absorb that $\hbar$ dependence into the redefinition of the integrands:

$$\begin{aligned}
\d{\Psi(q)}
&=\hbar^2\d{\overline{\Psi}(\bar{q})}
=\hbar^{\cancelto{2}{4}}\dh[4]{\bar{q}} 
\cancel{\frac{1}{\hbar}}\hat{\delta}(2p_1\cdot\bar{q}+\hbar\bar{q}^2)
\Theta(p^0_1+q^0) 
\cancel{\frac{1}{\hbar}}\hat{\delta}(2p_1\cdot \bar{q} +\hbar\bar{q}^2)
\Theta(p^0_2+q^0)
\end{aligned}$$
$$
\begin{aligned}


\overline{\mathcal{I}_\text{v}'}(O)&=\hbar^2\mathcal{I}_\text{v}'(O)\\
\overline{\mathcal{I}_\text{r}'}(O)&=\hbar^2\mathcal{I}_\text{r}'(O)
\end{aligned}$$

We can finally neatly write:

$$\Delta O=\AAngle{\int \d {\overline{\Psi}(\bar{q})}\exp\par[\big]{-\i\bar{q}^\mu b_\mu}\par[\Big]{\overline{\mathcal{I}_\text{v}'}(O)+\overline{\mathcal{I}_\text{r}'}(O)}}  $$

Now the $\hbar$ dependence is all in the integrands  (ignoring the $\hbar \bar{q}^2$ factors in the delta function). 

We can now explore the integrands in different theories: 

\acr{kmoc} in SQED

Let us use the \acr{kmoc} framework for scalar QED 

$$\Delta O=\AAngle{\int \d {\overline{\Psi}(\bar{q})}\exp\par[\big]{-\iunit\bar{q}^\mu b_\mu}\par[\Big]{\vKernAA{O}+\rKernAA{O}}}  $$

Let us take $p_\mu^1$ as the observable corresponding to the momentum of the first particle.

We then have: ^12c1d7

$$
\begin{aligned}
\vKernAA{p_\mu^1}&=\hbar^2\iunit\,  q\, \mathcal{A}(p_1,p_2 \to p_1+\hbar \bar{q},p_2-\hbar \bar{q})\\
\rKernAA{p_\mu^1}&=\hbar^2\cutint\ddP[2+\abs{X}]{r_1,r_2,r_X}(r_1^\mu-p_1^\mu)\,\hat{\delta}^{(4)}\left(p_{1}+p_{2}-r_{1}-r_{2}-r_{X}\right) \\
&\times   \mathcal{A}\left(p_{1}, p_{2} \rightarrow r_{1}, r_{2}, r_{X}\right) \mathcal{A}^{*}\left(p_1+\hbar \bar{q},p_2-\hbar \bar{q} \rightarrow r_{1}, r_{2}, r_{X}\right)
\end{aligned}$$


We can extract $\hbar$ from $q$ and from the amplitude, by extracting each $e$ along with an $\frac{1}{\sqrt{\hbar}}$ , thus quartic vertices yield a factor of $\frac{e^2}{\hbar}$ whereas cubic ones yield $\frac{e}{\sqrt{\hbar}}$.  If we count the number $V_3$ of all cubic vertices, and $V_4$ the number of quartic vertices we have that the number of internal lines is $I=\frac{1}{2}(3V_3+4V_4-E)$. This is because we have $3V_3+4V_4$  lines to start with, out of which $E$ are chosen to be external. The remaining $(3V_3+4V_4-E)$ ones are contracted among themselves to form $I$ internal lines. In our case we have $E=4+M$ where $M=\abs{X}$ is the number of messenger particles. Using the argument from loop counting we have that the number of loops of our graph $L$ is given by:
$$
\begin{aligned}
        L=I-V+N=&\frac{1}{2}(3V_3+4V_4-4-M)-V_4-V_3+1\\
=&\frac{1}{2}(V_3+2V_4)-1-\frac{M}{2}
\end{aligned}
$$
where $N$ is the number of connected topological space|connected components ($=1$ in our case) . Thus we see that the amount of extracted $\hbar$s corresponds directly to the number of loops plus one! We can thus write the amplitude $\mathcal{A}$ as a sum over reduced $L$-loop amplitudes $\bar{\mathcal{A}}^{(L)}$:

$$\mathcal{A}(p_1,p_2\to r_1,r_2,X)=\sum\limits_{L=0}^\infty\par[\Big]{\frac{e^{2}}{\hbar}}^{(L+1+\frac{\abs{X}}{2})}\bar{\mathcal{A}}^{(L)}(p_1,p_2\to r_1,r_2,X)$$


Going back to the integrands we have:

$$\begin{aligned}
\vKernAA{p_\mu^1}&=\hbar^3\iunit\,  \bar{q}\, \sum\limits_{L=0}^\infty\par[\Big]{\frac{e^{2}}{\hbar}}^{(L+1)}\bar{\mathcal{A}}^{(L)}(p_1,p_2\to p_1+\hbar \bar{q},p_2-\hbar\bar{q})\\
&=\iunit\,  \bar{q}\, \sum\limits_{L=0}^\infty e^{2(L+1)}{\hbar}^{(2-L)}\bar{\mathcal{A}}^{(L)}(p_1,p_2\to p_1+\hbar \bar{q},p_2-\hbar\bar{q})
\end{aligned}$$

as well as the real kernel:[^1]

$$\begin{aligned}

\rKernAA{p_\mu^1}&=\hbar^2\cutint\ddP[\abs {X}]{r_X}\prod\limits_{i=1,2}\dh[4]{w_i}\hat{\delta}(2p_i \cdot w_i+w_i^2)\Theta(p_i^0+w_i^0) \\
&\times w_1^\mu\,\hat{\delta}^{(4)}\left(w_1+w_2+r_{X}\right)
\\
&\times\mathcal{A}\left(p_{1}, p_{2} \rightarrow p_1+w_{1}, p_2+w_{2}, r_{X}\right) 
\mathcal{A}^{*}\left(p_1+\hbar \bar{q},p_2-\hbar \bar{q} \rightarrow p_1+w_{1}, p_2+w_{2}, r_{X}\right)\\
&
\end{aligned}$$
$$\begin{aligned}

=\hbar^2\cutint&\ddP[\abs {X}]{{r}_X}\prod\limits_{i=1,2}\hbar^3\dh[4]{\bar{w}_i}\hat{\delta}(2p_i \cdot \bar{w}_i+\hbar\bar{w}_i^2)\Theta(p_i^0+\hbar \bar{w}_i^0) \\
&\times   \hbar \bar{w}_1^\mu\,\hbar^{-4}\hat{\delta}^{(4)}\par[\big]{\bar{w}_1+\bar{w}_2+\frac{1}{\hbar}r_{X}}
\\
&\times\sum\limits_{L=0}^\infty\par[\Big]{\frac{e^{2}}{\hbar}}^{2L+2+\abs{X})}\bar{\mathcal{A}}^{(L)}\par{p_{1}, p_{2} \rightarrow p_1+\hbar\bar{w}_{1}, p_2+\hbar\bar{w}_2, r_{X}} 
\mathcal\\\\
&\times\bar{\mathcal{A^{*}}}^{(L)}{}\par{p_1+\hbar \bar{q},p_2-\hbar \bar{q} \rightarrow p_1+\hbar\bar{w}_{1}, p_2+\hbar\bar{w}_2, r_{X}}

\end{aligned}$$

$$\begin{aligned}
=\cutint&\ddP[\abs {X}]{{r}_X}\prod\limits_{i=1,2}\dh[4]{\bar{w}_i}\hat{\delta}(2p_i \cdot \bar{w}_i+\hbar\bar{w}_i^2)\Theta(p_i^0+\hbar \bar{w}_i^0) \\
&\times    \bar{w}_1^\mu\,\hat{\delta}^{(4)}\par[\big]{\bar{w}_1+\bar{w}_2+\frac{1}{\hbar}r_{X}}
\\
&\times\sum\limits_{L=0}^\infty e^{2(2L+2+\abs{X})}{\hbar}^{3-2L-\abs{X}}\bar{\mathcal{A}}^{(L)}\par{p_{1}, p_{2} \rightarrow p_1+\hbar\bar{w}_{1}, p_2+\hbar\bar{w}_2, r_{X}} 
\mathcal\\\\
&\times\bar{\mathcal{A^{*}}}^{(L)}{}\par{p_1+\hbar \bar{q},p_2-\hbar \bar{q} \rightarrow p_1+\hbar\bar{w}_{1}, p_2+\hbar\bar{w}_2, r_{X}}\\

\end{aligned}$$

Schematically we have 

$$\begin{aligned}
\vKernAA{p_\mu^1}&=\sum\limits_{L=0}^\infty \mathcal{O}(e^{2(L+1)})\\
\rKernAA{O}&=\sum\limits_{L=0}^\infty \mathcal{O}(e^{4(L+1)+2\abs{X}})
\end{aligned}$$

The contributions from the virtual kernel are lower order for a given loop order. Both kernels contribute together provided that the following equation is verified.

$$L-1=2L'+\abs{X}$$

Where $L$ is the loop count for the virtual kernel and $L'$, $\abs{X}$ are the real kernel loop count and messenger particle count respectively.

Now we see that the leading order contribution [^2]to the impulse $\Delta p_1^{\mu,(0)}$  can only be from the virtual kernel at tree level. Thus we have the following equation.

$$\Delta p_1^{\mu,(0)}=\AAngle{\int \d {\overline{\Psi}(\bar{q})}\exp\par[\big]{-\iunit\bar{q}^\mu b_\mu}\ \vKernAA{p_1^{\mu},L=0}} $$

And the integrand is given by the tree level 4 point amplitude.

$$\vKernAA{p_1^{\mu},L=0}=\iunit\,  \bar{q}^\mu\,  e^{2}{\hbar}^{2}\bar{\mathcal{A}}^{(0)}(p_1,p_2\to p_1+\hbar \bar{q},p_2-\hbar\bar{q})$$

The amplitude is read off from the single tree level diagram and using feynman rules for SQED. 

$$\iunit\bar{\mathcal{A}}^{(0)}(p_1,p_2\to p_1+\hbar \bar{q},p_2-\hbar\bar{q})=\iunit \frac{Q_1 Q_2 }{\hbar^2\bar{q}^2}\par[\big]{4 p_1 \cdot p_2+\hbar^2\bar{q}^2}$$

We can now safely take the $\hbar \to 0$ limit as the integrand contains no terms singular in $\hbar$ (the $\frac{1}{\hbar^2}$ is cancelled by the $\hbar^2$ pre-factor). Thus the classical limit is carried out and the final integral to compute is obtained. The integration measure is also simplified in the limit $\lim\limits_{\hbar \to0} \d{\overline{\Psi}(\bar{q})}=\dh[4]{\bar{q}} \hat{\delta}(2p_1\cdot\bar{q})\hat{\delta}(2p_1\cdot \bar{q} )$[^3]

$$\Delta p_1^{\mu,(0)}=e^2Q_1Q_2\int\dh[4]{\bar{q}} \hat{\delta}(2p_1\cdot\bar{q})\hat{\delta}(2p_1\cdot \bar{q} )\euler^{-\iunit\bar{q}\cdot b}\bar{q}^\mu \frac{4 p_1 \cdot p_2}{\hbar^2\bar{q}^2}$$

This can be analytically computed (see LO impulse SQED) to find a closed form for the leading order impulse.

$$\Delta p_1^{\mu,(0)}=-\frac{e^{2} Q_{1} Q_{2}}{2 \pi} \frac{\gamma}{\sqrt{\gamma^{2}-1}} \frac{b^{\mu}}{b^{2}}$$

For NLO impulse SQED, using the order equation above we have a 1-loop contribution from the virtual integrand as well as a tree level cut contribution from the real integrand. See NLO impulse SQED for details.
 


[^1]: We changed the integration variable from $r_i$ to $w_i=r_i-p_i$ thus the measure changes:$$\ddP[2+\abs{X}]{r_1,r_2,X}=\ddP[\abs {X}]{r_X}\prod\limits_{i=1,2}\dh[4]{w_i}\hat{\delta}(2p_i \cdot w_i+w_i^2)\Theta(p_i^0+w_i^0)$$ where we used the same reasoning as for the $q_i$ variable change.
    
[^2]: Here the expansion is in powers of the coupling constant, so even though we want $\hbar$s to cancel, the loop order will still affect the order of the contribution through the coupling constant $e$  and the leading order corresponds to $e^2$
[^3]: Compare to $$\d{\overline{\Psi}(\bar{q})}=\dh[4]{\bar{q}} \hat{\delta}(2p_1\cdot\bar{q}+\hbar\bar{q}^2)\Theta(p^0_1+q^0) \hat{\delta}(2p_1\cdot \bar{q} +\hbar\bar{q}^2)\Theta(p^0_2+q^0)$$The theta functions cancel as $q^0\to0$ and $p_i$ becomes classical.  And as discussed in classical limit of wavefuctions in \acr{kmoc} the integration implicit in the brackets yields new delta functions based on the classical momenta, and with the  $\bar{q}^2$s removed




[^2]: $f(x)=\int \ddP{p} \tilde{f}(\boldsymbol{p})\exp{-\frac{\i}{\hbar} p^\mu x_\mu}$. Then a shifted, i.e. translated version of $f(x)$ can be written:$$\begin{aligned}
f(x-x_0)&=\int \ddP{p} \tilde{f}(\boldsymbol{p})\,\exp{-\frac{\i}{\hbar} p_\mu (x^\mu-x_0^\mu)}\\
&=\int \ddP{p} \tilde{f}(\boldsymbol{p})\,\exp{\frac{\i}{\hbar}p_\mu x^\mu_0}\,\exp{-\frac{\i}{\hbar} p_\mu x^\mu}
\end{aligned}$$
Thus the associated, translated state is:
$$\ket{f}=\int \ddP{p} \tilde{f}(\boldsymbol{p})\,\exp{\frac{\i}{\hbar}p_\mu x^\mu_0}\,\ket{p }$$
[^3]: $1=\sum\limits_X \int \ddP[2+\abs{X}]{r_1,r_2,X}\dyad{r_1 r_2 X}$ Where we could consider the states ${r_1,r_2,X}$ to be the final states after the scattering
[^4]: Introducing the momentum shifts modifies the measure in the following way:
    $$\ddP{p_i'}=\ddP{p_i+q_i}=\dh[4]q_i\,\hat{\delta}((p_i+q_i)^2-m_i^2) \Theta(p^0_i+q_i^0)$$
            Now since we also have the on shell enforcing delta function from $\ddP{p_i}$ we can rewrite the delta functions:     $$\ddP{p_i}\,\hat{\delta}((p_i+q_i)^2-m_i^2)=\ddP{p_i}\hat{\delta}(\underbracket{(p_i^2-m_i^2)}_{\text{redundant}}+2 p_i \cdot q_i+q_i^2)=\ddP{p_i}\hat{\delta}(2 p_i \cdot q_i+q_i^2)$$
            Finally when integrating over $q_2$ we choose to hit $\hat{\delta}^{(4)}(p_1+p_2-p_1'-p_2')=\hat{\delta}^{(4)}(q_1+q_2)$ and thus we just set $q_2=-q_1$