# Conclusion {#sec-conclusion}

In this thesis, we explored the landscape of theoretical research that surrounds gravitational wave detection.  We showed the existence of gravitational waves theoretically. We motivated waveform generation techniques grounded in first principles' physics. It is only through such precise frameworks that we can hope to elucidate the nature of the objects that emit gravitational radiation. We looked at (?:nr)  and (?:eob)  two complementary approaches to waveform generation that enabled (?:ligo)  to make the field changing detection in 2016. Both approaches have their challenges, (?:nr)  with stability and computational cost, and (?:eob)  with higher order perturbative calculations. Each increase in precision enables a more precise match of the signal, enabling a much richer analysis of the incoming wave. Purely analytical tools have recently come into the crosshairs of particle physicits aswell.

 We then went on to understand these nascent formalisms built on techniques from particle physics. The (?:eft)  matching approach enables a simple map from (?:eob)  to amplitudes computed in the potential kinematic region. (?:eft), and (?:eob)  in general, struggle to use and implement dissipation however. The Hamiltonian framework has to be somehow augmented with the dissipative forces. This motivates frameworks that sidestep the (?:eob)  framework. We explored the most developed one currently: (?:kmoc) . We were able to express classical observables such as the impulse in terms of the classical limit amplitudes and their unitarity cuts. We then went on to implement a programmatic framework for expressing the necessary integrals that the amplitudes yield. We used custom code to apply Feynman rules, manipulate and filter the graphs. We matched the results from @Kosower:2018adc, and then implemented a scalar product reduction for preparing the input to IBP reduction programs.

 The results and formalisms explored here show that amplitude techniques in gravitational wave theory are a very promising and powerful tool. Much of the recent (?:hep) techniques can directly be put to use in this context, and can already outperfom traditional methods. The higher perturbative order frontier however is increasingly difficult. At some point in the near future, these computations will have exhausted the techniques currently in use for particle physics. The next step is to develop new techniques that can be applied to both fields. Important work needs to be done to have a fully amplitude based waveform generation framework. This might be the next revolution in gravitational wave theory.