# Waveform Generation

::: {.content-visible unless-format="pdf"}

{{< include _latexmacros.qmd >}}

:::

The matched filtering approach introduced in the previous section is a powerful tool for detecting signals in noise. Additionally, if the matching signal has some physical content, that same content can be expected to describe the emitting object with reasonable error. Ideally the matching signal is entirely constructed from first priciples, thus when a match is obtained the physical inputs to the model 


The matched filtering approach introduced in the previous section motivates tools for generating waveforms. These can be varied in physical content, but also in practicality. In all cases they need to be able to cover the set of parameters (the parameter space) that one is interested in exploring. Clearly if the waveform has been generated purely heuristically, then the physical content of the detection is close to zero. One can only say one has detected a phenomenon that produces this waveform, but not much more. However, if the input parameters are physically meaningful, like the mass ratio of a binary compact inspiraling system, then the waveform constructed purely from this input, if matched to the signal, tells us that a compact binary inspiraling system with this mass ratio has been detected. However, the waveform generation must be able to cover the whole parameter space (in this case all feasible mass ratios) to be useful, as one does *not* know the parameters of the object one is looking for.  Ideally this waveform generation can be done in a way that is computationally efficient, as the number of parameters to explore can be large. In the end, currently, waveform generation is done in a hybrid way, where some waveforms at some parameter space points are generated from first principles, and the rest of the parameter space waveforms are interpolated. 

In this chapter we will look at the physically motivated waveform generation tools currently being developed in research. More specifically we are going to explore techniques for compact binary waveforms, as these are currently the objects to which \acr{ligo} and others are most sensitive to (see @sec-ligo) and by far the most common emitters of high intensity \acr{gw}s. As discussed in @sec-compactbinaries, orbiting and \acr{gw} emitting compact objects will necessarily inspiral and merge at somepoint. 

For such inspiraling binaries, the waveform has three distinct parts, corresponding to distinct phases of a binary merger: a first inspiral phase, a merger phase where a remnant compact body is produced as a result of the coalescence of the two objects, and a postmerger, or ringdown phase where the remnant still emits gravitational radiation while settling to its new stable configuration. Each phase has specific characteristics in the dynamics of the objects and thus correspondingly different frameworks are aimed at specific portions of the waveforms. Even within one phase, different regimes and thus frameworks exist, additionally dependent to the type/initial state of the two orbiting bodies.

## \acr{nr}

The most successful physically motivated waveform-generation technique to date is numerical relativity (\acr{nr}). Pionneered by ..., it is the backbone of all other methods and is used to calibrate against. The idea is simple: \acr{efe} are a system of coupled partial differential equations (PDEs) (albeit quite nonlinear) that can be solved numerically by discretizing the fields involved, i.e. the metric in this case. Of course the story is not all that simple as the aforementioned non-linearities increase the stability requirements of any numerical scheme. Additionally, the gauge freedom that simplified the derivation in the last chapter, when discretized can play a leading role in the collapse of the numerical scheme. Finally, when compact binary objects are considered, the scales involved further complicate discretization, as one needs enough resolution to resolve the objects, as well as a large enough volume to have reasonable orbits. This leads to a huge amount of points in the model, meaning such simulations are very computationally expensive. All these factors conspire to make any sizable bank of \acr{nr} waveforms a very expensive endeavor. To date only a couple hundred parameter space points have been simulated. With these \acr{ligo} and others have been able to interpolate between parameter space points to reach the ones needed for detection. However, with the advent of \acr{lisa} on the horizon, a further problem will arise. \acr{nr} results by nature only take into actount the last few orbit cycles before merger. Any more than that, and computational time becomes prohibitive. \acr{lisa} with its low noise floor should be able to detect inspiraling bu not yet merging binaries. To do so however will require waveform templates with hundreds of orbits, well out of reach from any modern \acr{nr} package. Nonetheless, this technique has shown and will continue to show its worth, as no approximations other than discretization are made. This means that these waveforms are seen as the gold standard for the field, and thus are used to calibrate the other waveform generation techniques. 

## Inspiral phase 

The inspiral phase is the first phase of a binary merger. During this phase the two objects are still orbiting each other, and orbital approximations become valid. A whole family of frameworks have been developed to model this phase, each applying various different simplifying assumptions to turn the full \acr{efe} into a tractable problem. The first approximation, we have already encountered in a simple form. It is the essentially a weak field approximation or \acr{pm} approximation. One expands the metric around the background Minkowski metric, and then the \acr{efe} are expanded in perturbation orders. One can further expand in velocities, if we consider relatively slow moving objects, which is applicable to compact orbiting objects. This is called the \acr{pn} approximation. A very different approximation can be applied when the mass ratio of the object in question is large. Here one can expand around a fixed but *not* flat mertric, essentially considering one of the objects as a test -particle evolving on a background caused by the heavier object. This is called the \acr{gsf} formalism. Finally, one approach takes into account all  the results from the previous approximations, and fits them into a single object, applicable in all regimes. This is the \acr{eob} framework.




### \acr{pm}


### \acr{pn}

### \acr{gsf}

### \acr{eob}

As it's name suggests, the \acr{eob} framework tries to combine all the previous data into a hamitonian describing the motion of a single body. It was pioneered in @Buonanno:1998gg. The idea comes from Newtonian binaries where the method to solve the two body problem is to turn it into a one body problem. Consider two bodies, with masses $\mass[1]$ and $\mass[2]$, positions $\tv[1]{q}$, $\tv[1]{q}$ and momenta $\tv{\emom[1]}$ and $\tv{\emom[2]}$ respectievly. The system can be described by the following hamiltonian:

$$
\ham[\text{newton}]{\tv[1]{q},\tv[1]{q}}{\tv{\emom[1]},\tv{\emom[2]}}= \frac{\tv{\emom[1]}^2}{2\mass[1]}  + \frac{\tv{\emom[2]}^2}{2\mass[2]}  - \frac{G\mass[1]\mass[2]}{\abs{\tv[1]{q}-\tv[1]{q}}}
$$

One then transforms this hamitionan into one descibing the relative motion $\tv{q}=\tv[1]{q}-\tv[1]{q}$. One can formalise this by defining a new set of generalised coordinates, through a canonical transformation. We can even go further and employ a generating function for the transformation, ensuring that hamiton's equations stay unchanged (see @goldsteinClassicalMechanics2002). To descibe relative motion, we use jacobi coordinates $(\tv{Q},\tv{q})$:
$$
\begin{pmatrix} \tv[1]{q} \\ \tv[1]{q}\end{pmatrix}\to \underbrace{\begin{pmatrix} \frac{\mass[1]}{\totmass} & \frac{\mass[2]}{\totmass} \\ 1&-1 \end{pmatrix}}_{A} \begin{pmatrix} \tv[1]{q} \\ \tv[1]{q}\end{pmatrix}=\begin{pmatrix} \tv{Q} \\ \tv{q}\end{pmatrix}
$${#eq-jacobi2}

If we now define the following generating function for the transformation, depending on the old positions coordinates  $\tv{q_i}$ and the new momenta $\tv{P_i}$: [note the use of einstein summation]{.aside}

$$
f_{II}(\tv{q_i},\tv{P_i})=\tv{P_i}A^{ij}\tv{q}_j
$${#eq-genfunc}

Then the old momenta is given by: 

$$
\tv{\emom[i]}=\pdv{f_{II}}{\tv{q_i}}=\tv{P_i} A^{ij} \iff \tv{P_i}=[A^{-1}]{}^{ij}\tv{\emom[i]}
$${#eq-momtrans}
Where we can directly invert this equation and obtain the new momenta as:

$$
  \begin{pmatrix} \tv{P} \\ \tv{p}\end{pmatrix}=\begin{pmatrix} \tv{P_1} \\ \tv{P_2}\end{pmatrix}=\begin{pmatrix} 1&1\\ \frac{\mass[2]}{\totmass} & -\frac{\mass[1]}{\totmass} \end{pmatrix} \begin{pmatrix} \tv{\emom[1]} \\ \tv{\emom[2]}\end{pmatrix}
$$
 
Where as expected we obtain that one of the momenta descibes the center of mass momentum $\tv{P}=\tv{\emom[1]}+\tv{\emom[2]}$. The other positions are by constuction given by $\pdv{f_{II}}{\tv[1]{q}}=\tv{Q}$ and $\pdv{f_{II}}{\tv[1]{q}}=\tv{q}$ i.e the same as equation @eq-jacobi2. Finally the new hamitonian $\ham[\text{rel}]{\tv{Q},\tv{q}}{\tv{P},\tv{p}}$ can be directly obtained by the generating function:^[We just plug in the definition of the old momenta in terms of the new (@eq-momtrans):
$$ \tv{\emom[1]}=\frac{\mass[1]}{\totmass} \tv{P} + \tv{p}$$
$$ \tv{\emom[2]}=\frac{\mass[2]}{\totmass} \tv{P} - \tv{p}$$
]

$$
\ham[\text{rel}]{\tv{Q},\tv{q}}{\tv{P},\tv{p}}=\ham[\text{newton}]{\tv{Q},\tv{q}}{\tv{P},\tv{p}}+\cancelto{0}{\pdv{f_{II}}{t}}= \frac{\tv{P}^2}{2\totmass}  + \frac{\tv{p}^2}{2\redmass}  - \frac{G\mass[1]\mass[2]}{\abs{\tv{q}}}
$$
Where $\totmass = \mass[1] + \mass[2]$ is the total mass, and $\redmass = \frac{\mass[1]\mass[2]}{\totmass}$ is the reduced mass. If we move to a frame where the $\tv{Q}$ is at rest, i.e. $\tv{P}=0$ the hamiltonian colapses to a one body hamiltonian. The two-body problem we started with has can now be though of as the one body problem of a test-particle of mass $\redmass$ orbiting an external mass $\totmass$. 

The \acr{eob} framework takes the above derivation and generalises it to general relativity. The defining trick used above is to transform to 'better' coordinates. A first step is to demand that for straight line motion the \acr{com} energy $E_{\text{\small COM}}=\ct[0]{P}$, where $P$ it the 4-momentum of the entire-system, is equal to the hamiltonian. We have then:^[In the \acr{com} frame, the spacial part of the total momentum is zero (by defintion), and thus we have:
$$
\co[0]{P}^2=P^2=(\emom[1]+\emom[2])^2=\emom[1]^2+\emom[2]^2+2\emom[1]\cdot\emom[2]
$$]

$$
\mathcal{H}=\sqrt{\totmass^2(1+2\symmratio(\lorentzfactor-1))}
$$

Where $\symmratio=\frac{\redmass}{\totmass}$ is the symmetric mass ratio, and $\lorentzfactor=\frac{1}{\sqrt{1-{v^2}}}=\frac{\ct{\emom[1]}\co{\emom[2]}}{\mass[1]\mass[2]}$ is the relative lorentz-factor. Note that for noninteracting systems we have $\co{\emom}\ct{\emom}=\redmass^2$ and we can call the effective hamitonian:

$$
\Heff=\ct[0]{\emom}=\sqrt{\redmass^2+\tv{\emom}^2} = \redmass \lorentzfactor
$${#eq-straightheff}

And then we can substitute this into the hamiltonian above, and add back a generic system momentum $\tv{P}$ and obtain:

$$
\Heob=\sqrt{\totmass^2(1+2\symmratio(\frac{\Heff}{\redmass}-1))+\tv{P}^2}
$$


This hamitlonian (with $\Heff$ given by @eq-straightheff) now describes straight line motion in a relativistic framework. The key point is that we can take $\Heff$ to be a gravitational test mass hamiltionian, with some specific deformations and this will match the \acr{PN} result. This is more than a neat trick as this hamiltonian when well matched fits the gold standard \acr{nr} result up to the merger, well out of the \acr{PN} regime. Curcially this hamiltaanian framework does not take into actont radiation reaction by construction (since it is based on conserved energy). 
## Merger and Ringdown phase

### \acr{eob}