#
# file generated by qgraf-3.4.2
#
#  output= './QGRAFout/julia/bfrb.jl' ;
#  style= './styles/julia.sty' ;
#  model= './qgraf/SQEDmodel';
#  in= phi1,  phi2;
#  out= phi1c,phi2c;
#  loops=           1 ;
#  loop_momentum= k;
#  options=  notadpole,nosnail,onshell ;
#

diags=[
]

